CI用のgithub actionを用意しました
skanehira/chibiwasm pull request #12
Opened 2023-05-01 15:43 UTC by stmtk1

何故かcargo-makeが使えなかったので、cargo testでtestするようにしました

2023-05-01 15:52 UTC, stmtk1 commented
close#8

2023-05-02 12:36 UTC, skanehira requested changes

2023-05-02 12:36 UTC, skanehira commented on .github/workflows/main.yml
> +        uses: ./.github/actions/docker
https://techblog.paild.co.jp/entry/2023/04/10/170218

いくつかsetup用のactionsがあるので、dockerではなくそちらを使ってほしいです

2023-05-02 14:47 UTC, skanehira commented on .github/workflows/main.yml
>        - name: clippy checkout
リポジトリを clone しているだけなので clippy とは関係ないですね
```suggestion
      - name: checkout
```

2023-05-02 14:49 UTC, skanehira commented on .github/workflows/main.yml
> +  clippy:
clippy というよりは lint という job ですね

```suggestion
  lint:
```

2023-05-02 14:50 UTC, skanehira commented on .github/workflows/main.yml
> +        id: clippy
このidってどこかで使う予定ですか？
見た感じ必要なさそう

2023-05-02 14:51 UTC, skanehira commented on .github/workflows/main.yml
> +      - name: Get clippy result
```suggestion
      - name: Run clippy
```

2023-05-02 14:52 UTC, skanehira commented on .github/workflows/main.yml
> +      - name: test checkout
```suggestion
      - name: checkout
```

2023-05-02 14:52 UTC, skanehira commented on .github/workflows/main.yml
> +      - name: Test action step
```suggestion
      - name: Setup rust toolchain
```

2023-05-02 14:53 UTC, skanehira commented on .github/workflows/main.yml
> +      - name: Get test result
```suggestion
      - name: Run test
```

2023-05-04 14:14 UTC, stmtk1 commented on .github/workflows/main.yml
> +        id: clippy
idは必要ないので消しました

2023-05-04 15:47 UTC, skanehira approved these changes
LGTM
ありがとうございます

2023-05-04 15:48 UTC, merged